# DS 3000 HW 1 

Due: Tuesday Sep 18 @ 11:59 PM EST

### Submission Instructions
Submit this `ipynb` file to Gradescope (this can also be done via the assignment on Canvas).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to gradescope.

### Tips for success
- Start early
- Make use of Piazza (also accessible through Canvas)
- Make use of Office Hours
- Remember to use cells and headings to make the notebook easy to read (if a grader cannot find the answer to a problem, you will receive no points for it)
- Under no circumstances may one student view or share their ungraded homework or quiz with another student [(see also)](http://www.northeastern.edu/osccr/academic-integrity), though you are welcome to **talk about** (*not* show each other your answers to) the problems.

# Part 1 (25 points): Markdown in Jupyter

Use the markdown language below to create your own brief wikipedia-esque description of any subject of interest. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a table of size at least 3 rows x 3 columns (needn't be correct, but must make sense)
- a list
- a link to another website

Please be brief in your text.  Aim for roughly 3 sentences total of text.  We won't grade based on content, but keep it appropriate for class.  If you make the grader smile, no extra credit will be awarded beyond the satisfaction of having made somebody's day better :)

# This is a Heading

## With a Subheading Under It

    - This is a list
    - Of minimal length
    - With several points to make
    - And a bonus extra item
    
I wasn't really sure what to write about so I just made it something random. I'll add another sentence to increase the length of the text. And another that's more interesting than the last.

### A Smaller Subheading
[And a link to the NY Times](https://www.nytimes.com)

| Color  | Fruit  | Status | Cost |
|--------|--------|--------|------|
| Red    | Apple  | Ripe   | 4    |
| Green  | Pear   | Ripe   | 3    |
| Yellow | Banana | Ripe   | 1    |

![alt text](https://images.unsplash.com/photo-1598755257130-c2aaca1f061c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2lsZCUyMGFuaW1hbHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80)

# Part 2: Lists and Flow and Functions, Oh my! 
## Part 2.1: Manual Data Entry (20 points)

**Beware**: to complete this part of the assignment, you *must* do it during a weekday when the stock market is open!

How would you collect data on a stock's performance without a computer doing it automatically? Go to [this website](https://www.tradingview.com/) and look up a stock (any stock). You are going to write a function that takes live input of the stock's value (entered by you), saves all inputs in a list, stops once you enter 10 values **or** three consecutive decreasing values (whichever comes first), and returns the values.

For this problem:

- Call your function `my_stock`
- Make sure that you use the `input()` option within your function to accept entries
- Make sure you are saving all entries in a list
- Use `if-else` and a `while` loop
- When you have written the function, call:

`manual_data_entry = my_stock()`

`manual_data_entry`

and click between (or have the pages open side by side) this notebook and the stock to manually enter the stock's value over time (the website updates every 5 seconds).

**Note**: There may be multiple ways to get this function to work, but to receive full points, your function **must** have the five components listed above.

In [1]:
def my_stock():
    """ collects stock data in a list. returns after 10 inputs or three consecutive decreasing values
    
    Returns:
        data (list): stock values over time
        
    """
    data = []
    
    count = 0
    while count < 10:
        value = float(input("What is the current value of the stock? "))
        data.append(value)
        
        # test for three consecutive decreasing values
        if data[count] < data[count - 1] < data[count - 2]:
            break
        else:
            count += 1
        
    return data

In [2]:
manual_data_entry = my_stock()

manual_data_entry

What is the current value of the stock? 176.27
What is the current value of the stock? 176.27
What is the current value of the stock? 176.28
What is the current value of the stock? 176.30
What is the current value of the stock? 176.29
What is the current value of the stock? 176.28


[176.27, 176.27, 176.28, 176.3, 176.29, 176.28]

## Part 2.2: Thinking (5 pts)

In a markdown (text) cell, discuss at least **two** drawbacks to using the function you wrote in Part 2.1 to collect the data the way we did. Make sure you **discuss** the drawbacks, instead of simply listing them. What did we do that was sub-optimal and how could we improve it?

# Part 3: Numpy
## Part 3.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [3]:
# make sure to import numpy library
import numpy as np

In [4]:
array_a = np.array([[3, 8, -2, 3],
                   [.5, -1, 6, 4],
                   [-5, 7, -42, 2]])

array_b = np.array([[42, 38, 34],
                    [30, 26, 22],
                    [18, 14, 10],
                    [6, 2, -2],
                    [-6, -10, -14]])

In [5]:
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [6]:
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 3.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b`, then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [7]:
# array a stats
print(array_a.shape)
print(array_a.size)
print(array_a.ndim)
print(array_a.nbytes)

(3, 4)
12
2
96


In [8]:
# array b stats
print(array_b.shape)
print(array_b.size)
print(array_b.ndim)
print(array_b.nbytes)

(5, 3)
15
2
60


In [9]:
# transpose array a and b
t_array_a = np.transpose(array_a)
t_array_b = np.transpose(array_b)

In [10]:
# adding arrays
np.add(array_a, t_array_b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 

In [11]:
# delete a column from t_array_b
t_array_b = np.delete(t_array_b, 4, 1)

In [12]:
# adding arrays part two
np.add(array_a, t_array_b)

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

In order to add two numpy arrays together, both arrays have to have the same length. The reason adding the two arrays didn't work the first time was because t_array_b was longer by one column. By removing this colomn, the two arrays were the same shape and were able to be added together.

# Part 4: Pandas Pokémon
## Part 4.1: Reading in Data (5 points)

On Canvas is the `pokedata.csv` file. Read this data set in, using the `Pokedex` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [13]:
# make sure to import pandas library
import pandas as pd

In [14]:
df_pokedex = pd.read_csv("pokedata.csv") 

df_pokedex.set_index("Pokedex", inplace = True)

df_pokedex.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense  
Pokedex                   
1            49       49  
2            62       63  
3            82       83  
4            52       43  
5            64       58

## Part 4.2: Manipulating Data (20 points)

1. Add a new column to the data set that calculates the BMI of the Pokémon. The formula for BMI using Imperial Units (such as these data contain) is = $703 \times \frac{Weight}{Height^2}$. Print the first few rows.
    - Find out which Pokémon have (a) the highest BMI and (b) the lowest BMI.
1. Create a subset of the Pokémon Data that you created in (1) which (a) includes only Pokémon that have `BaseSpeed >= 60` and (b) **excludes** all Pokémon with the Grass `MainType`. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the **full** Pokémon Data from the data from (1). Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [15]:
# 1.
bmi_series = []

# iterate over every row, extract height and weight, and calculate
for index, row in df_pokedex.iterrows():
    height = row["Height"]
    weight = row["Weight"]
    bmi = 703 * (weight / (height ** 2))
    bmi_series.append(bmi)

df_pokedex["BMI"] = bmi_series

df_pokedex.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense        BMI  
Pokedex                              
1            49       49  30.756250  
2            62       63  13.265023  
3            82       83  24.837606  
4            52       43  22.823090  
5            64       58  15.930611

In [16]:
# Highest BMI
index = df_pokedex["BMI"].argmax()
df_pokedex.iloc[index, :]

Pokemon               Golem
MainType             Ground
SecondaryType          Rock
Height                   55
Weight                661.4
Damage                   80
BaseSpeed                45
Attack                  120
Defense                 130
BMI              153.707174
Name: 76, dtype: object

In [17]:
# Lowest BMI
index = df_pokedex["BMI"].argmin()
df_pokedex.iloc[index, :]

Pokemon           Haunter
MainType            Ghost
SecondaryType      Poison
Height                 63
Weight                0.2
Damage                 45
BaseSpeed              95
Attack                 50
Defense                45
BMI              0.035425
Name: 93, dtype: object

In [18]:
# 2.

# filter basespeed and maintype, then print
df_filtered = df_pokedex[(df_pokedex["BaseSpeed"] >= 60) & (df_pokedex["MainType"] != "Grass")]
df_filtered.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   
6         Charizard     Fire        Flying      67   199.5      78        100   
9         Blastoise    Water           NaN      63   188.5      79         78   
12       Butterfree      Bug        Flying      43    70.5      60         70   

         Attack  Defense        BMI  
Pokedex                              
4            52       43  22.823090  
5            64       58  15.930611  
6            84       78  31.242704  
9            83      100  33.387629  
12           45       50  26.804489

In [19]:
# 3.
df_pokedex.describe()

Height       Weight      Damage   BaseSpeed      Attack  \
count  151.000000   151.000000  151.000000  151.000000  151.000000   
mean    46.894040   100.766954   64.218543   68.933775   72.913907   
std     37.880717   131.299070   28.585519   26.746880   26.755421   
min      8.000000     0.200000   10.000000   15.000000    5.000000   
25%     28.000000    21.800000   45.000000   46.500000   51.000000   
50%     39.000000    66.100000   60.000000   70.000000   70.000000   
75%     59.000000   124.250000   80.000000   90.000000   92.000000   
max    346.000000  1014.100000  250.000000  140.000000  134.000000   

          Defense         BMI  
count  151.000000  151.000000  
mean    68.225166   32.764506  
std     26.916704   23.189403  
min      5.000000    0.035425  
25%     50.000000   20.856877  
50%     65.000000   30.042735  
75%     84.000000   38.245600  
max    180.000000  153.707174

the .describe() function only ran on seven of the ten original columns. it's missing the pokemon, maintype, and secondarytype columns. that's because these columns contain **categorical data**. the .describe() function excluded these columns because it can only calculate statistics on **numerical data**, as shown above.