# Lab1: Tic-Tac-Toe

### Instructions:
- perform a fresh `restart & run all` before submitting
- [lab rubric](https://course.ccs.neu.edu/ds2500/admin_syllabus.html?highlight=rubric#weekly-lab-ds-2501)

## Goal

Build a tic-tac-toe script which is capable of allowing two people to play tic tac toe by inputting their choices into the computer.  It may help to see example input / output in Part C to get a sense of how things will be put together before starting.


# You are given `get_position()`

Use the `get_position()` function below to get a user's desired position.


In [1]:
import numpy as np

def get_position(player_idx):
    """ gets a user's move via input().  no user input validation
    
    see also: get_apply_input()
    
    Args:
        player_idx (int): player idx (used to call 
            the player by name)

    Returns:
        row_idx (int): a row index
        col_idx (int): a col index
    """
    # get input from user
    pos = input(f'player {player_idx} input position: ')
    
    # parse user's input
    row_idx, col_idx = pos.split(',')
    row_idx = int(row_idx)
    col_idx = int(col_idx)
    
    return row_idx, col_idx

# Part A: `get_apply_input()`

Using the `get_position()` function above, complete the `get_apply_input()` function below.

In [2]:
def get_apply_input(board, player_idx):
    """ gets input from user and applies their mark
    
    re-query if input given does not refer to a 
    position on the board currently marked as board_null
    
    Args:
        board (np.array): a 3x3 tic-tac-toe board
        player_idx (int): player whose turn is being taken
            (either 1 or 2)
            
    Returns:
        board (np.array): a 3x3 tic-tac-toe board
            which has recorded 
    """    
    assert player_idx in (1, 2), 'invalid player_idx'
    
    # query user
    if True:
        row_idx, col_idx = get_position(player_idx)
        assert board[row_idx, col_idx] == 0, "occupied square"
       
    # update board
    board[row_idx, col_idx] = player_idx
    return board

# Part B: `get_win_set()`

Complete the `get_win_set()` function below.

In [3]:
def get_win_set(board):    
    """ returns a set of winning values in a board
    
    Args:
        board (np.array): a square tic-tac-toe board
        
    Returns:
        win_set (set): a set of items which fill an
            entire row, column, diagonal or off-diagonal
            (off-diagonal is top-right to bottom-left)
    """
    win_set = set({})
    
    # test horizontal and veritcal
    for i in range(3):
        row = set(board[i])
        col = set(board[:, i])
        
        if len(row) == 1:
            win_set.add(row.pop())  
        if len(col) == 1:
            win_set.add(col.pop())
    
    # test diagonal and reverse diagonal
    diag = set(np.diagonal(board))
    rdig = set(np.fliplr(board).diagonal())
    
    if len(diag) == 1:
        win_set.add(diag.pop())
    elif len(rdig) == 1:
        win_set.add(rdig.pop())
    
    # win set
    return win_set

In [4]:
assert get_win_set(board=np.zeros((3, 3))) == {0}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [2, 2, 2]])) == {0, 1, 2}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 2, 2],
                                   [1, 2, 2]])) == {1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 0, 0],
                                   [1, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 1, 0],
                                   [0, 1, 0],
                                   [0, 1, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 0, 1],
                                   [0, 0, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 1, 1],
                                   [0, 0, 0],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [0, 0, 0],
                                   [1, 1, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [0, 1, 0],
                                   [0, 0, 1]])) == {1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 1, 0],
                                   [1, 0, 0]])) == {1}

# Part C: Putting it all together in `play_tic_tac()`

Complete the function `play_tic_tac()` below which plays tic-tac-toe.  In addition to the example output shown below, the game should also stop if there are not any valid moves remaining.

In [7]:
import numpy as np

def play_tic_tac():
    """ plays a game of tic-tac-toe on a 3x3 board
    
    """
    board = np.zeros((3, 3))
    
    while True:
        for i in range(1, 3):
            print(board)
            board = get_apply_input(board, i)
            win_set = get_win_set(board)
            
            z = set([i])
            if set(z).issubset(win_set):
                print(board)
                print(f"player {i} wins!")
                return
            

In [8]:
play_tic_tac()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
player 1 input position: 1,1
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
player 2 input position: 0,2
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
player 1 input position: 2,2
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 1.]]
player 2 input position: 1,0
[[0. 0. 2.]
 [2. 1. 0.]
 [0. 0. 1.]]
player 1 input position: 0,0
[[1. 0. 2.]
 [2. 1. 0.]
 [0. 0. 1.]]
player 1 wins!
